<<<<<<< HEAD
name: aplikasi_presensi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  location: ^5.0.3
  syncfusion_flutter_maps: ^24.1.41
  http: ^1.3.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.1.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/dk.jpg
    - assets/cky.jpg
    - assets/presensi.jpg
    - assets/avatar.jpg
=======
name: aplikasi_presensi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  location: ^5.0.3
  syncfusion_flutter_maps: ^24.1.41
  http: ^1.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3
  google_fonts: ^6.1.0
  shimmer: ^2.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/dk.jpg
    - assets/cky.jpg
    - assets/presensi.jpg
<<<<<<< HEAD
>>>>>>> 9ee284c (first commit)
=======
    - assets/avatar.jpg
>>>>>>> aa3c1be (add)
